version: '2'
services:
  userservice-app:
    image: userservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://userservice-postgresql:5432/UserService
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  userservice-postgresql:
    extends:
      file: postgresql.yml
      service: userservice-postgresql
