version: '2'
services:
  userservice-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/UserService/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=UserService
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
