version: '2'
services:
  gateway-app:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgresql:5432/Gateway
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8888:8888
  gateway-postgresql:
    extends:
      file: postgresql.yml
      service: gateway-postgresql
